### ISSUE TITLE
Wrong function result of readRaw

### ISSUE THREAD

**Issue by Edzelf** [djuseeq/Ch376msc#29]
The result of the function readRaw is always "1".  Shouldn't that be the number of bytes read by this function?

**Comment by djuseeq** [comment]
Hi, yes that is true, the function returns 0 when all the data has been read out, otherwise 1. When i started to develop this lib, it was a good solution for me but later as i further developed the code i realized i should have solved it differently. On Arduino forum i have posted a [message](https://forum.arduino.cc/index.php?topic=663402.msg4521177#msg4521177) regarding this problem

**Comment by Edzelf** [comment]
That clear.  Thank you for you comment.
